### PR TITLE
Exception patch.. again

### PR DESCRIPTION
**Pull request by AmyJeanes**
Sorry shouldn't have created the original pull req until I was 100% sure everything was good

This just fixes the case where the check throws an exception and then the next time it runs it fails again because it assumes the 'TestEMailToken' is in the last run data and throws an exception trying to access it, repeat ad infinitum.

### CODE REVIEW

**Comment by AmyJeanes** [comment]
Hold up on merging this.. just want to make sure things are working good first 👍

**Comment by AmyJeanes** [comment]
Okay looks stable, go ahead 😄

**Review by Shawson — COMMENTED** [review]
looks good to me!

**Comment by tidusjar** [comment]
I've been waiting for this feature! Thanks ❤️

**Pull request merged**
